Add filenames to cibuild script

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,12 +1,13 @@
 #!/bin/sh
 
+errors=0
 for filename in ../geojson/*.geojson; do
 	result=$(curl -X POST --data @$filename $data http://geojsonlint.com/validate 2>/dev/null)
 	if [ "$result" = "{\"status\": \"ok\"}" ]; then
-		echo "Valid GeoJSON!"
+		echo $filename "passed GeoJSON validation."
 	else
-		echo "Invalid GeoJSON"
-		exit 1
+		echo $filename "FAILED GeoJSON validation."
+		errors=1
 	fi
 done
-exit 0
+exit $errors
